config/routes.rb
Rails.application.routes.draw do  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if (Rails.env.production?)
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :protocol => "http://" }
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :subdomain => "" }
  end

  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "/resume" => "pages#resume"

  resources :users, except: [:signup]
  resources :articles, except: [:signup]
  resources :categories, except: [:destroy]
  resources :books, except: [:signup]
  resources :projects, except: [:signup]
  # resources :research, except: [:signup]
  resources :book_categories
  resources :posts, only: [:index]
  resources :stocks

  get "login" => "sessions#login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # get "resources", to: "pages#resources"
  # get "projects", to: "pages#projects"
  # get 'signup', to: 'users#signup'
  # get 'readinglist', to: 'pages#readinglist'
  # get "quotes", to: "pages#quotes"
  # get "about", to: "pages#about"
  # get "search_stocks", to: "stocks#search"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :restrict

  def index
    #@articles = Article.all
    @articles = Article.order("created_at desc")
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.where(role: "master")
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully obliterated"
    redirect_to articles_path
  end

  private

  def restrict
    if not master_logged_in?
      redirect_to root_path
    end
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :editor1, :description, category_ids: [])
  end
end

app/views/articles/_article.html.erb
<div class="text-center p-1">
  <% obj.each do |article| %>
  <a href="<%= article_path(article) %>" class="no-underline burgandy">
    <div class="bg-white block border border-gray-300mx-auto my-8 py-10 rounded shadow hover:shadow-lg sm:w-3/4">
      <h1 class="fancy-font burgandy"><%= article.title %></h1>
      <div class="leading-normal normal-font p-8 text-black text-lg">
        <% if article.description.blank? then %>
          <%= truncate(strip_tags(article.editor1), length: 600) %>
        <% else %>
          <%= truncate(strip_tags(article.description), length: 600) %>
        <% end %>
      </div>
      <small class="block burgandy mx-auto px-6">Created by <%= article.user.username if article.user %>
        <%= time_ago_in_words(article.created_at) %> ago,
        Last updated: <%= time_ago_in_words(article.updated_at) %> ago
      </small>
      <% if article.categories.any? %>
      <p class="py-6 normal-font"> Categories: <%= render article.categories %> </p>
      <% end %>
      <div class="justify-center mx-auto py-2 sm:flex sm:w-3/4 md:w-1/2">
        <% if logged_in? %>
        <%= link_to "Edit", edit_article_path(article), class: "bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg text-green-900 w-48" %>
        <%= link_to "Destroy", article_path(article), method: :delete,
                              data: {confirm: "Are you sure you want to delete the article?"},
                              class: "bg-white block border border-red-800hover:bg-red-900 hover:text-red-600-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48" %>
        <% end %>
      </div>
    </div>
  </a>
  <% else %>
  <%= nil %>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="bg-white container mx-auto rounded shadow-lg p-6">
  <%= form_for @article do |f| %>
  <%= form_for(@article, :html => {role: "form"}) do |f| %>
  <div class="">


  </div>
  <div class="w-3/4 mx-auto">
    <%= f.text_field :title, placeholder: "Title of Article", autofocus: true,
            class:"form-title block border border-red-900 focus:border-red-900 focus:shadow-lg p-4 rounded shadow text-center w-full" %>
  </div>

  <div class="w-3/4 mx-auto block border border-red-900 focus:border-red-900 focus:shadow-lg my-12 rounded shadow">
    <%= f.text_area :body, rows: 27, placeholder: "Body", id: "editor1" %>
    <!-- <textarea name="editor1" id="editor1" rows="27" class="form-description" placeholder="Body"></textarea> -->
  </div>

  <div class="category-boxes py-6 text-center">
    <h3 class="pb-6 burgandy text-2xl underline">Category</h3>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <%= cb.label(class: "inline-flex mx-6 normal-font text-lg burgandy") {cb.check_box(class: "checkbox mr-2") + cb.text} %>
    <% end %>
  </div>

  <%= f.submit class: "py-3 bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font rounded shadow-lg text-green-900 w-48" %>
  <% end %>
  <% end %>

  <div class="py-16 text-center">
    <%= link_to "Cancel Request and Return to Articles Listing", articles_path, class: "burgandy fancy-font hover:underline no-underline" %>
  </div>
</div>

<% content_for :javascripts do %>
<script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
<script>CKEDITOR.replace('editor1');</script>
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function () {
    $('form[data-remote]').bind('ajax:before', function () {
      for (instance in CKEDITOR.instances) {
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<% end %>

app/views/articles/edit.html.erb
<section class="edit-article pb-16">
    <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Edit Existing Article</h1>
    <%= render 'form' %>
</section>

app/views/articles/index.html.erb
<section class="articles py-16">
  <h1 class="fancy-font burgandy text-center">Blog</h1>
  <div class="mx-auto py-4 sm:flex sm:w-1/2 text-center">
    <% if logged_in? %>
      <%= link_to "Create New Article", new_article_path, class: "bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg text-green-900 w-48" %>
    <% else %>
      <%= nil %>
    <% end %>
    <a href="<%= categories_path %>"
      class="bg-white block border border-red-800hover:bg-red-900 burgandy hover:text-red-600-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48">
      Categories
    </a>
    <a href="<%= posts_path %>"
      class="bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg text-green-900 w-48">
      Medium Articles
    </a>
  </div>

  <%= render 'article', obj: @articles %>
</section>

app/views/articles/new.html.erb
<section class="new-article pb-16">
<h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Create an Article</h1>
<%= render 'form' %>
</section>

app/views/articles/show.html.erb
<section class="article-show py-16">
  <div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg mx-auto p-6">
      <h1 class="burgandy fancy-font pb-16 pt-8 text-center"><%= @article.title %></h1>
      <div class="w-3/4 mx-auto pb-6 normal-font leading-loose xl:text-lg text-gray-900" id="article">
        <% if @article.description.blank? then %>
          <%= simple_format(@article.editor1) %>
        <% else %>
          <%= @article.description %>
        <% end %>
      </div>
      <% if @article.categories.any? %>
      <p class="normal-font text-black text-center py-4">Categories: <%= render @article.categories%></p>
      <% end %>

      <div class="md:w-4/5 mx-auto py-4 sm:flex text-center">
        <% if logged_in? %>
        <%= link_to "Edit this Article", edit_article_path(@article), 
          class: "py-3 bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font rounded shadow-lg text-green-900 w-48" %>
        <%= link_to "Destroy this Article", article_path(@article), method: :delete,
            data: {confirm: "Are you sure you want to destroy the article?"},
            class: "bg-white block border border-red-800hover:bg-red-900 burgandy hover:text-red-600-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48" %>

        <%= link_to "View all Articles", articles_path, 
          class: "bg-white block border border-blue-800text-blue-600 button hover:text-blue-100 hover:bg-blue-900 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48"%>

        <% else %>
        <%= link_to "View all Articles", articles_path, 
          class: "bg-white block border border-red-800hover:bg-red-900 burgandy hover:text-red-600-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48"%>
        <% end %>
      </div>
    </div>
  </div>
</section>