config/routes.rb
Rails.application.routes.draw do  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if (Rails.env.production?)
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :protocol => "http://" }
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :subdomain => "" }
  end

  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "/resume" => "pages#resume"

  resources :users, except: [:signup]
  resources :articles, except: [:signup]
  resources :categories, except: [:destroy]
  resources :books, except: [:signup]
  resources :projects, except: [:signup]
  # resources :research, except: [:signup]
  resources :book_categories
  resources :posts, only: [:index]
  resources :stocks

  get "login" => "sessions#login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # get "resources", to: "pages#resources"
  # get "projects", to: "pages#projects"
  # get 'signup', to: 'users#signup'
  # get 'readinglist', to: 'pages#readinglist'
  # get "quotes", to: "pages#quotes"
  # get "about", to: "pages#about"
  # get "search_stocks", to: "stocks#search"

end

app/views/partials/_admin_nav.html.erb
<nav id="admin-nav" class="bg-gray-900 w-full z-50 py-2">
  <ul class="list-style-none relative w-5/6 mx-auto flex justify-end">
    <li class="admin-link text-white w-24 text-center hover:bg-black p-1 rounded relative">
      <a href="#" class="text-white no-underline">Article</a>
      <ul class="admin-dropdown px-0 list-style-none bg-gray-900 w-24 z-50">
        <li class="hover:bg-black p-1 w-full"><%= link_to "Index", articles_path, class: "text-white no-underline"%></li>
        <li class="hover:bg-black p-1 w-full"><%= link_to "New", new_article_path, class: "text-white no-underline"%></li>
        <li class="hover:bg-black p-1 w-full"><%= link_to "Categories", categories_path, class: "text-white no-underline"%></li>
        <li class="hover:bg-black p-1 w-full"><%= link_to "New Category", new_category_path, class: "text-white no-underline"%></li>
      </ul>
    </li>
    <li class="admin-link text-white w-24 text-center hover:bg-black p-1 rounded relative">
      <a href="#" class="text-white no-underline">Post</a>
      <ul class="admin-dropdown px-0 list-style-none bg-gray-900 w-24 z-50">
        <li class="hover:bg-black p-1 w-full"><%= link_to "Index", posts_path, class: "text-white no-underline"%></li>
      </ul>
    </li>
    <li class="admin-link text-white w-24 text-center hover:bg-black p-1 rounded relative">
      <a href="#" class="text-white no-underline">Book</a>
      <ul class="admin-dropdown px-0 list-style-none bg-gray-900 w-24 z-50">
        <li class="hover:bg-black p-1 w-full"><%= link_to "New", new_book_path, class: "text-white no-underline"%></li>
        <li class="hover:bg-black p-1 w-full"><%= link_to "New Category", new_book_category_path, class: "text-white no-underline"%></li>
        <li class="hover:bg-black p-1 w-full"><%= link_to "Book Categories", book_categories_path, class: "text-white no-underline"%></li>
      </ul>
    </li>
    <li class="admin-link text-white w-24 text-center hover:bg-black p-1 rounded relative">
      <a href="#" class="text-white no-underline">Project</a>
      <ul class="admin-dropdown px-0 list-style-none bg-gray-900 w-24 z-50">
        <li class="hover:bg-black p-1 w-full"><%= link_to "New", new_project_path, class: "text-white no-underline"%></li>        
      </ul>
    </li>
    <li class="admin-link text-white w-24 text-center hover:bg-black p-1 rounded relative">
      <a href="#" class="text-white no-underline">Stock</a>
      <ul class="admin-dropdown px-0 list-style-none bg-gray-900 w-24 z-50">
        <li class="hover:bg-black p-1 w-full"><%= link_to "Index", stocks_path, class: "text-white no-underline"%></li>
      </ul>
    </li>
    <li class="admin-link w-24 text-center hover:bg-black p-1 rounded relative">
      <%= link_to "Log Out", logout_path, method: :delete, class: "text-white no-underline"%>
    </li>
  </ul>
</nav>

app/views/partials/_footer.html.erb
<footer class="py-4 hidden relative text-center w-full bg-white">
    <div class="container mx-auto">
        <p class="block normal-font text-center text-sm">
            No copyright, take whatever you want. <a href="https://alextheyounger.me" class="burgandy">alexyounger.me</a> by Alex Younger. This site was built with Ruby on Rails and TailwindCSS.
        </p>
        <p class="block normal-font text-center text-sm">Fractal terrain generator javascript adapted from <a href="https://codepen.io/ge1doot/pen/ZPpWaR" rel="nofollow" target="_blank" class="burgandy">https://codepen.io/ge1doot/pen/ZPpWaR</a>.</p>
        <div class="flex sm:block py-4 text-center w-full">
            <a href="<%= $linkedin %>" class="w-16 no-underline burgandy fa fa-lg fa-linkedin"></a>
            <a href="<%= $facebook %>" class="w-16 no-underline burgandy fa fa-lg fa-facebook"></a>
            <a href="<%= $twitter %>" class="w-16 no-underline burgandy fa fa-lg fa-twitter"></a>
            <a href="<%= $github %>" class="w-16 no-underline burgandy fa fa-lg fa-github"></a>
            <a href="<%= $codepen %>" class="w-16 no-underline burgandy fa fa-lg fa-codepen"></a>        
            <a href="<%= $medium %>" class="w-16 no-underline burgandy fa fa-lg fa-medium"></a>
            <a href="mailto:<%= $email %>" class="w-16 no-underline burgandy fa fa-lg fa-envelope-o"></a>
        </div>
    </div>
</footer>

app/views/partials/_language_bar.html.erb
<div id="language-bar" class="text-lg mx-auto lg:w-3/4 home-content js--fadeInLeft p-8">
  <h2 class="mb-3 text-3xl text-grey-darkest fancy-font">Skills</h2>
  <span class="bar w-full mb-4">
    <% if @languageStats.is_a? Hash then %>
      <% languageStats.each do |lang, val| %>
        <span style="width: <%= val %>%" class="bar-item <%= GithubLanguage.slugifyLanguage(lang) %>"></span>
      <% end %>
    </span>
    <ul class="flex flex-wrap">
      <% languageStats.each do |lang, val| %>
        <li class="lang-item w-48">
          <div class="item-wrapper inline-flex flex-nowrap no-underline text-sm mr-3">
            <svg class="octicon <%= GithubLanguage.slugifyLanguage(lang) %> octicon-dot-fill mr-2" viewbox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8z"></path>
            </svg>
            <span class="lang-name mr-1"><%= lang %></span>
            <span><%= val %>%</span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="float-right italic">
    <small>Pulled directly from Github</small>
  </div>
</div>

app/views/partials/_nav.html.erb
<nav class="bg-white relative desktop fancy-font py-8 w-full z-20">
    <div class="container flex justify-between mx-auto">    
        <a href="<%= root_path %>" class="w-3/5 nav-link fancy-font no-underline text-2xl burgandy">Home</a>
        <div class="w-2/5 flex justify-end md:w-2/3">        
            <a href="<%= books_path %>" class="nav-link fancy-font no-underline mr-8 text-2xl burgandy">Reading List</a>
            <a href="<%= projects_path %>" class="nav-link fancy-font no-underline text-2xl burgandy">Projects</a>            
        </div>
    </div>
</nav>

<nav class="mobile">
    <div class="mobile-nav-button absolute m-8 right-0 z-50 top-0 w-8 h-8">
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
    </div>

    <div class="mobile-menu block max-w-md w-full h-screen top-0 z-negative absolute bg-red-700<% if current_page?(root_path) %> bg-blue <% end %>">
        <ul class="relative p-0 hidden">
            <li><a href="<%= root_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-100">Home</a></li>            
            <li><a href="<%= books_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-100">Reading List</a></li>
            <li><a href="<%= projects_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-100">Projects</a></li>            
        </ul>
    </div>
</nav>

app/views/partials/_navigation.html.erb
<nav class="bg-white desktop fancy-font py-8 relative z-10">
    <div class="container flex justify-between mx-auto">    
        <a href="<%= root_path %>" class="w-3/5 nav-link fancy-font no-underline text-2xl burgandy">Home</a>
        <div class="w-2/5 flex justify-end md:w-2/3">        
            <a href="<%= books_path %>" class="nav-link fancy-font no-underline mr-8 text-2xl burgandy">Reading List</a>
            <a href="<%= projects_path %>" class="nav-link fancy-font no-underline text-2xl burgandy">Projects</a>            
        </div>
    </div>
</nav>

<nav class="mobile">
    <div class="mobile-nav-button absolute m-8 pin-r z-50 pin-t w-8 h-8">
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
        <div class="mobile-nav-button__line w-full relative bg-black"></div>
    </div>

    <div class="mobile-menu block max-w-md w-full h-screen pin-t z-negative absolute bg-red-dark <% if current_page?(root_path) %> bg-blue <% end %>">
        <ul class="relative p-0 hidden">
            <li><a href="<%= root_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-lightest">Home</a></li>            
            <li><a href="<%= books_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-lightest">Reading List</a></li>
            <li><a href="<%= projects_path %>" class="w-full max-w-2xl fancy-font mx-auto block text-center relative text-4xl my-3 font-bold text-blue-lightest">Projects</a></li>            
        </ul>
    </div>
</nav>

app/views/partials/_projects-carousel.html.erb
<h3 class="text-3xl text-gray-900 mb-4 fancy-font mx-auto">Projects</h3>
<div class="projects-carousel">
  <% if @projects.any?
      then %>
    <% @projects.each do |project| %>
      <div class="carousel-cell">
        <a href="<%= project.project_link%>" target="blank" rel="nofollow" class="no-underline normal-font w-full h-full px-4">
          <div class="bg-gray-200 h-full relative">
            <h2 class="font-normal text-center text-black py-2"><%= project.title%></h2>
            <div class="image py-4 mx-auto">
              <% if (project.screens.attached?) %>
                <picture>
                  <source srcset="<%= project.get_webp_attachment %>" type="image/webp">
                  <source srcset="<%= project.get_jpeg_attachment %>" type="image/jpg">
                  <img src="<%= project.get_jpeg_attachment %>" class="w-full" alt="<%= project.image_alt %>"/>
                </picture>
              <% else %>
                <picture>
                  <source srcset="<%= image_path("#{project.image_address}.webp") %>" type="image/webp">
                  <source srcset="<%= image_path("#{project.image_address}") %>" type="image/jpg">
                  <img src="<%= image_path("#{project.image_address}") %>" class="w-full" alt="<%= project.image_alt %>"/>
                </picture>
              <% end %>
            </div>
            <div class="excerpt p-2">
              <p class="leading-normal text-center text-sm normal-font pb-4 text-black">
                <%= project.excerpt.present? ? project.excerpt : project.description %>
              </p>
              <h4 class="normal-font text-center text-black">Built with
                <span class="<%= project.assign_color %>"><%= project.framework%></span></h4>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  <% end %>
</div>
<a href="<%= projects_path %>" class="bg-white block
  border
  border-blue-800
  hover:bg-blue-900
  hover:text-blue-100
  mx-auto text-center
  no-underline
  normal-font
  py-3
  rounded
  shadow-lg
  text-blue-900
  w-48
  mt-12">

  See More
</a>