config/routes.rb
Rails.application.routes.draw do  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if (Rails.env.production?)
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :protocol => "http://" }
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :subdomain => "" }
  end

  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "/resume" => "pages#resume"

  resources :users, except: [:signup]
  resources :articles, except: [:signup]
  resources :categories, except: [:destroy]
  resources :books, except: [:signup]
  resources :projects, except: [:signup]
  # resources :research, except: [:signup]
  resources :book_categories
  resources :posts, only: [:index]
  resources :stocks

  get "login" => "sessions#login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # get "resources", to: "pages#resources"
  # get "projects", to: "pages#projects"
  # get 'signup', to: 'users#signup'
  # get 'readinglist', to: 'pages#readinglist'
  # get "quotes", to: "pages#quotes"
  # get "about", to: "pages#about"
  # get "search_stocks", to: "stocks#search"

end

app/models/project.rb
require "mini_magick"
require "colorize"

class Project < ActiveRecord::Base
  has_many_attached :screens

  def get_webp_attachment
    self.screens.each do |screen|
      type = screen.blob.content_type
      if (type == "image/webp")
        if (Rails.env.production?)
          return screen.service_url
        end
        if (Rails.env.development?)
          return Rails.application.routes.url_helpers.rails_blob_path(screen, only_path: true)
        end
      end
    end
    return false
  end

  def get_jpeg_attachment
    self.screens.each do |screen|
      type = screen.blob.content_type
      if (type == "image/jpeg")
        if (Rails.env.production?)
          return screen.service_url
        end
        if (Rails.env.development?)
          return Rails.application.routes.url_helpers.rails_blob_path(screen, only_path: true)
        end
      end
    end
    return false
  end

  def attach_screens(params)
    if (params.present?)
      webpObj = WebpConverter.generate_attachment_webp(params[:project][:screen])
      self.screens.attach(params[:project][:screen])
      self.screens.attach(io: File.open(webpObj.first), filename: webpObj.last, content_type: "image/webp")
      if (self.screens.attached?)
        puts "#{self.title} screens attached".green
        return true
      end

      return false
    end
  end

  def update_screens(params)
    if (params.present?)
      webpObj = WebpConverter.generate_attachment_webp(params[:project][:screen])
      self.screens.attach(params[:project][:screen])
      self.screens.attach(io: File.open(webpObj.first), filename: webpObj.last, content_type: "image/webp")
      if (self.screens.attached?)
        puts "#{self.title} screens attached".green
        return true
      end

      return false
    end
  end

  def seed_screens(img)
    if (img.present?)
      self.screens.attach(io: File.open("app/assets/images/#{img}"), filename: img, content_type: "image/jpg")
      webpBlob = ActiveStorage::Blob.create_after_upload!(io: File.open("app/assets/images/#{img}.webp"), filename: "#{img}.webp", content_type: "image/webp")
      self.screens.attach(webpBlob)
      if (self.screens.attached?)
        puts "#{self.title} screens attached".green
        return true
      end

      return false
    end
  end

  def reorder_positions
    i = self.position.clone
    Project.where("position >= ?", i).order(:position).each do |project|
      next if (self.id == project.id)
      i += 1
      project.update(position: i)
    end
  end

  def assign_color
    colors = {
      "ruby-on-rails" => "text-red-600",
      "php-laravel" => "text-blue-600",
      "php" => "text-blue-600",
      "wordpress" => "text-blue-700",
      "python" => "text-yellow-700",
      "net" => "text-gray-700",
    }

    lang = self.framework.parameterize

    return colors[lang]
  end
end

app/controllers/projects_controller.rb
load "app/modules/webp_converter.rb"
require "mini_magick"

class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :restrict, except: :index

  def index
    @projects = Project.order(:position)
    @languageStats = GithubLanguage.calculateWidths
    set_meta_tags title: "Projects",
                  site: "alextheyounger.me",
                  description: "Alex Younger - My projects. Some of my greatest projects",
                  reverse: true,
                  image_src: ActionController::Base.helpers.asset_path("bluehawaiian.jpg"),
                  og: {
                    title: "Projects",
                    url: "#{Rails.root}projects",
                    image: ActionController::Base.helpers.asset_path("bluehawaiian.jpg"),
                  },
                  twitter: {
                    card: "Alex Younger - Projects. Some of my greatest projects",
                    site: "@AlextheYounga",
                  }
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.image_address = params[:project][:screen].original_filename.to_s
    @project.image_alt = "Alex Younger Projects List #{params[:project][:title]} in #{params[:project][:framework]}"
    if (@project.save)
      @project.attach_screens(params)
      @project.reorder_positions
      flash[:notice] = "Project was successfully created"
      redirect_to projects_path
    else
      render "new"
    end
  end

  def update
    if (@project.update(project_params))
      @project.reorder_positions
      if (params[:project][:screen])
        @project.screens.purge
        @project.attach_screens(params)
      end
      flash[:notice] = "Project was successfully updated"
      redirect_to projects_path
    else
      render "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project was successfully obliterated"
    redirect_to projects_path
  end

  private

  def restrict
    if not master_logged_in?
      redirect_to root_path
    end
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(
      :title,
      :description,
      :excerpt,
      :image_address,
      :image_alt,
      :project_link,
      :framework,
      :position
    )
  end
end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

<div class="bg-white container mx-auto rounded shadow-lg p-6">
  <%= form_for(@project, :html => {role: "form"}) do |f| %>
  <div class="w-3/4 mx-auto my-6">
    <%= f.text_field :title, placeholder: "Project Title", autofocus: true, class:"form-title block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
  </div>
  <div class="w-3/4 flex mx-auto mb-6">
    <%= f.text_area :excerpt, rows: 5, placeholder: "Excerpt", class: "form-excerpt block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
  </div>
  <div class="w-3/4 flex mx-auto">
    <%= f.text_area :description, rows: 15, placeholder: "Description", class: "form-description block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
  </div>
  <div class="flex justify-between w-3/4 mx-auto my-6">
    <div class="w-2/3">
      <%= f.text_field :framework, placeholder: "Project Framework", autofocus: true, class:"form-framework block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
    </div>
    <div class="w-1/6">
      <%= f.text_field :position, placeholder: "Position", autofocus: true, class:"form-position block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
    </div>
  </div>
  <div class="w-3/4 mx-auto my-6">
    <%= f.text_field :project_link, placeholder: "Project Link", autofocus: true, class:"form-link block border border-red-900 focus:border-red-900 focus:shadow-lg p-3 rounded shadow w-full" %>
  </div>
  <div class="w-3/4 flex justify-center mx-auto">
    <div class="screen-photo w-1/3 shadow py-6 rounded px-2 text-center ">
      <p class="mb-4">Screen Photo</p>
      <%= f.file_field :screen %>
    </div>
  </div>
</div>

<%= f.submit class: "py-3 bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font rounded shadow-lg text-green-900 w-48" %>
<% end %>

<div class="py-16 text-center">
<%= link_to "Cancel Request and Return to Reading List", projects_path, class: "burgandy fancy-font hover:underline no-underline" %>
</div>

app/views/projects/edit.html.erb
<section class="edit-project pb-16">
    <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Edit Existing Project</h1>
    <%= render 'form' %>
</section>

app/views/projects/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium fancy-font mb-4 text-gray-900">Projects</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Here are some of my proudest projects, personal and professional.</p>
    </div>
    <div class="flex flex-wrap -m-4">
      <% if @projects.any?
      then %>
        <% @projects.each do |project| %>
          <div class="lg:w-1/3 sm:w-1/2 p-4">
            <div class="flex relative">
              <% if (project.screens.attached?) %>
                <picture>
                  <source srcset="<%= project.get_webp_attachment %>" type="image/webp">
                  <source srcset="<%= project.get_jpeg_attachment %>" type="image/jpg">
                  <img src="<%= project.get_jpeg_attachment %>" class="absolute inset-0 w-full h-full object-cover object-center" alt="<%= project.image_alt %>"/>
                </picture>
              <% else %>
                <picture>
                  <source srcset="<%= image_path("#{project.image_address}.webp") %>" type="image/webp">
                  <source srcset="<%= image_path("#{project.image_address}") %>" type="image/jpg">
                  <img src="<%= image_path("#{project.image_address}") %>" class="absolute inset-0 w-full h-full object-cover object-center" alt="<%= project.image_alt %>"/>
                </picture>
              <% end %>
              <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                <% if master_logged_in? %>
                  <div class="absolute right-0 top-0 w-36 justify-between">
                    <a href="<%= edit_project_path(project) %>" class="bg-blue-600 edit-project-link hover:bg-blue-700 hover:underline no-underline px-3 py-2 rounded-b shadow text-white w-12">Edit</a>
                    <%= link_to "Destroy", project_path(project), method: :delete, data: {confirm: "Are you sure you want to destroy this project?"}, class: "bg-red-600 edit-project-link hover:bg-red-700 hover:underline no-underline px-3 py-2 rounded-b shadow text-white" %>
                  </div>
                <%end %>
                <h2 class="tracking-widest text-sm title-font font-medium text-red-500 mb-1"><%= project.framework%></h2>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= project.title%></h1>
                <p class="leading-relaxed"><%= project.excerpt.present? ? project.excerpt : project.description %></p>
                <a href="<%= project.project_link%>" class="text-red-500 inline-flex items-center">Visit
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewbox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/new.html.erb
<section class="new-project pb-16">
  <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Create Project</h1>
  <%= render 'form' %>
</section>