config/routes.rb
Rails.application.routes.draw do  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if (Rails.env.production?)
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :protocol => "http://" }
    # match "*path" => redirect("https://www.alextheyounger.me/%{path}"), :constraints => { :subdomain => "" }
  end

  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "/resume" => "pages#resume"

  resources :users, except: [:signup]
  resources :articles, except: [:signup]
  resources :categories, except: [:destroy]
  resources :books, except: [:signup]
  resources :projects, except: [:signup]
  # resources :research, except: [:signup]
  resources :book_categories
  resources :posts, only: [:index]
  resources :stocks

  get "login" => "sessions#login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # get "resources", to: "pages#resources"
  # get "projects", to: "pages#projects"
  # get 'signup', to: 'users#signup'
  # get 'readinglist', to: 'pages#readinglist'
  # get "quotes", to: "pages#quotes"
  # get "about", to: "pages#about"
  # get "search_stocks", to: "stocks#search"

end

app/models/category.rb
#Model for Categories
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :restrict, only: [:new, :edit]
  
  def index
    @categories = Category.all
  end
  
  def create
    @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category was successfully created"
        redirect_to categories_path
      else
        render 'new'
      end
  end
  
  def new
    @category = Category.new
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Name was successfully updated"
      redirect_to categories_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.order("created_at desc")
  end
  
  
  private
    def category_params
      params.require(:category).permit(:name)
    end
  
    def restrict
      if not master_logged_in?
        redirect_to root_path
      end
    end
  
end

app/views/categories/_category.html.erb
<% if current_page?(root_path) %>
<span>
  <%= link_to category.name, category_path(category), 
      class: "bg-blue-800hover:bg-blue-900 m-2 no-underline p-1 rounded text-blue-100 normal-font" %> &nbsp;
</span>
<% else %>
<span>
  <%= link_to category.name, category_path(category), 
      class: "bg-red-800hover:bg-red-900 m-2 no-underline p-1 rounded text-red-600-100 normal-font" %> &nbsp;
</span>
<% end %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<!-- Without initiation in categories_controller,                                                  this will not work-->
<div class="container mx-auto">
  <%= form_for(@category, :html => {role: "form"}) do |f| %>
  <div class='w-1/2 mx-auto'>
    <%= f.text_field :name, placeholder: "Category Name", autofocus: true,
           class: "form-title block border border-red-900 focus:border-red-900 focus:shadow-lg p-4 rounded shadow text-center w-full"%>
  </div>

  <%= f.submit class: 'py-3 bg-white block border border-green-800 hover:bg-green-900 hover:text-green-100 mx-auto my-4 no-underline normal-font rounded shadow-lg text-green-900 w-48' %>
  <% end %>

  <div class="py-16 text-center">
    <%= link_to "Cancel Request and Return to Articles Listing", articles_path, 
    class: "burgandy fancy-font hover:underline no-underline" %>
  </div>

app/views/categories/edit.html.erb
<!-- Category Edit Page -->
<section class="edit-category pb-16">
    <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Edit Category Name</h1>
    <%= render 'form' %>
</section>

app/views/categories/index.html.erb
<section class="category-index pb-16">
  <div class="pb-8 pt-16">
    <h1 class="fancy-font text-center burgandy">Article Categories</h1>
    <% @categories.each do |category| %>
      <div class="bg-white flex justify-between container mx-auto py-1 px-4 rounded-lg shadow-lg text-center w-1/2 my-2">
        <div class="flex justify-between w-1/4">
          <%= link_to "#{category.name}", category_path(category), class: "burgandy no-underline text-lg self-center" %>
          <p class="self-center"><%= pluralize(category.articles.count, "article") %></p>
        </div>
        <div class="w-1/2">
          <% if master_logged_in? %>
            <small><%= link_to "Edit", edit_category_path(category), class: "block hover:text-green-900 mx-auto my-4 no-underline text-green-800w-48 text-center" %></small>
          <% else %>
            <%= nil %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="py-16 text-center">
      <%= link_to "Return to Articles Listing", articles_path, class: "burgandy fancy-font hover:underline no-underline" %>
    </div>
  </section>

app/views/categories/new.html.erb
<section class="new-category pb-16">
    <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy">Create a New Category</h1>
    <%= render 'form' %>
</section>

app/views/categories/show.html.erb
<section class="category-show pb-16">
    <h1 class="sm:text-3xl font-medium text-2xl py-16 normal-font text-center burgandy"><%="Articles In: " + @category.name %></h1>
    <%= render 'articles/article', obj: @category_articles %>

    <%= link_to "View All", articles_path, class: "bg-white block border border-red-800hover:bg-red-900 burgandy hover:text-red-600-100 mx-auto my-4 no-underline normal-font py-3 rounded shadow-lg w-48" %>
</section>